### ISSUE TITLE
Nokogiri fails to load

### ISSUE THREAD

**Issue by mradzinski** [idleberg/atomizr.rb#1]
Tried running the example:

```
ruby atomizr --input=AS/AppleScript.sublime-completions --output=completions.cson

D:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
    from D:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from D:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.3.1-x64-mingw32/lib/nokogiri.rb:29:in `rescue in <top (required)>'
    from D:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.3.1-x64-mingw32/lib/nokogiri.rb:25:in `<top (required)>'
    from D:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
    from D:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
    from D:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
    from atomizr:6:in `<main>'
```

**Comment by idleberg** [comment]
Will have to test this on a virtual machine. Did you `gem install nokogiri`?
